#Application URL
url = https://complaints.joburgombudsman.org.za/About



#Run browser in headless mode
headless = false

#Credentials
username = admin
password = admin123

#ImplicitWait (in seconds)
implicitWait = 30

#ExplicitWait
explicitWait = 30